import test from 'node:test'
import assert from 'node:assert/strict'
import {mkdir,mkdtemp,writeFile,readFile,rm} from 'node:fs/promises'
import {join} from 'node:path'
import {CapabilityStore,checkFrozen} from '../lib/v2/core.js'
import {installSeed,develop} from '../lib/v2/runner.js'
for(const mode of ['batch','autonomous','guided'])test(`continuous DSH curriculum: ${mode} timing, task isolation and context continuity`,{skip:process.env.ROUTER_V2_PROFILE_TEST!=='1'},async t=>{
 const shared=process.env.ROUTER_V2_SHARED;await mkdir(shared,{recursive:true});const base=await mkdtemp(join(shared,'curriculum-')),root=join(base,'root'),snap=join(base,'snap');await mkdir(root);await mkdir(snap);t.after(()=>rm(base,{recursive:true,force:true}));await writeFile(join(root,'a.txt'),'initial\n')
 const store=new CapabilityStore(root);await installSeed(store,{enabled:true,image:'python@sha256:9d2e5553305c7c7b0097999bb17187c69b921ccd6bc9d40e4bb5ebe652c00285',pythonVersion:'3.13.15',dockerContext:process.env.ROUTER_DOCKER_CONTEXT??'colima',snapshotDirectory:snap,pids:64,triggerTimeoutMs:5000});const prior=(await store.read()).active.files
 const auth=join(base,'auth.json'),loader=join(base,'loader.mjs'),journal=join(base,'requests.jsonl');await writeFile(auth,JSON.stringify({apiKey:'offline-only',baseURL:'https://starter-test.invalid/v1'}),{mode:0o600});await writeFile(loader,`process.env.CURRICULUM_MOCK_MODE=${JSON.stringify(mode)};process.env.CURRICULUM_MOCK_JOURNAL=${JSON.stringify(journal)};await import(${JSON.stringify(new URL('./mock-curriculum-provider.js',import.meta.url).href)})`)
 const curriculum={mode:mode==='guided'?'autonomous':mode,...(mode==='guided'?{guidance:'responsibility',finishControl:'agent'}:{}),batchSize:1,tasks:[{id:'first',request:'Count first task lines.',files:{'a.txt':'a\nb\n'}},{id:'second',request:'SECOND_TASK_UNSEEN_EARLY count lines.',files:{'a.txt':'a\nb\nc\n'}}]}
 const r=await develop(store,{authFile:auth,loader,maxCalls:20,curriculum});assert.equal(r.status,'complete',JSON.stringify(r));assert(r.curriculumComplete,JSON.stringify(r));const s=await store.read(),c=s.sessions[r.sid].curriculum;assert.deepEqual(c.answers.map(x=>x.answer),['2','3']);assert.notEqual(s.active.files,prior);assert.equal(s.history.length,2);assert.equal(c.decisions.filter(x=>x.trigger).length,mode==='batch'?2:1);assert(c.decisions.filter(x=>x.trigger).every(x=>x.trigger===(mode==='batch'?'scheduler':'agent')))
 const calls=(await readFile(journal,'utf8')).trim().split('\n').map(JSON.parse);assert(!JSON.stringify(calls[0]).includes('SECOND_TASK_UNSEEN_EARLY'));if(mode==='guided')assert(JSON.stringify(calls[0]).includes('both responsibilities'));const last=JSON.stringify(calls.at(-1));assert(last.includes('Count first task lines.'));assert(last.includes('SECOND_TASK_UNSEEN_EARLY'));assert(last.includes('wc -l'));assert.equal(s.events.filter(e=>e.type==='capability-agent-turn').length,0);const f=await store.freeze();await checkFrozen(store,f)
})
