import {Curriculum} from './curriculum.js'
import {readFile} from 'node:fs/promises'
import {CapabilityStore} from './core.js'
import {Development} from './development.js'
import {assert} from '../schema.js'
import {hash} from '../rule-contract.js'
import {event} from '../store.js'
export const name='autonomous-development'
export const inject=['tools','llm','systemPrompt']
export function apply(ctx,settings){
 const store=new CapabilityStore(settings.root),dev=new Development(store,settings.sid),installed=new WeakMap()
 const curriculum=settings.curriculum?new Curriculum(store,settings.sid,settings.curriculum):null
 ctx.tools.guard(exec=>{const bodies=exec.agent&&installed.get(exec.agent);if(!bodies||ctx.tools.get(exec.name,exec.agent)?.execute!==bodies.get(exec.name))return 'Only isolated development tools are available'})
 ctx.systemPrompt.section({name:'autonomous-development',order:10000,text:`${curriculum?`Complete a chronological stream of tasks in ONE ongoing conversation. Keep your previous tool results and work context. Every task must be solved through solve; the router is bypassed during training. Request the first task with training(action='next'). Submit its exact result with training(action='submit',answer=...). Only the current task is disclosed. You have ${settings.maxCalls} total model calls, including solving and development. Do not finish your response until training returns done:true. Task tools return observed results only, never evaluator answers. ${settings.curriculum.mode==='autonomous'?"You may improve the persistent router when YOU judge accumulated experience warrants the effort. No scheduled reminders will be given. Choose training(action='begin_development',reason=...) to use development tools, then end_development to resume the current task. Skipping all development is allowed.":"After each batch, training offers a development interval. Decide what, if anything, to develop; end_development skips or closes it. Outside those intervals, solve tasks and accumulate experience."} You choose reusable capabilities, tests and publication. Development has cost; do not assume every task warrants a change.`:`You are developing a persistent pre-LLM deterministic router. Use the normal coding loop: inspect, reason, edit, execute commands, write tests, diagnose and decide what is worth retaining. You choose the capability families and development checks. No benchmark answers or hidden tests are supplied. You may finish without changes if the current code already suffices. This session has at most ${settings.maxCalls??64} model calls. Inspect the observed route metadata: already-automated correct-looking work usually does not warrant redevelopment unless you find a concrete defect. Allocate effort to uncovered reusable work; reserve time to publish. You decide, and no benchmark correctness label is provided.`}

Your filesystem tools and bash share an isolated Linux workspace. /work/task is a writable public task copy; /work/capabilities contains editable active Python packages; /work/history/observed.json contains actual past requests, assistant outputs and tool trajectories (NOT verified correct answers); /work/scratch is yours. No internet, host paths, credentials, evaluator, hidden future tasks or native harness modifications are accessible. Files persist across tool calls. In curriculum mode /work/task is the initial development example, while solve exposes the CURRENT immutable task at /testbed. Prior observed outputs and commands are in history; do not assume initial files match later tasks. All development and validation has cost.
A capability directory contains manifest.json (version:2,id,effect:'public-workspace-read',operations mapping operation names to args/result bounded JSON schemas and format integer/text/lines/json), parser.py parse(request,context), executor.py execute(task,context), CONTRACT.md and tests/cases.json. Inspect working packages as runnable examples. Parser returns {status:'parsed',task:{operation,args},evidence:{original,spans:[{field,start,end,text}],defaults:[],unexplained:[]}} or {status:'unsupported'/'ambiguous',reasons:[]}. Spans use JavaScript UTF-16 offsets. Executor returns {status:'completed',value:...} or {status:'fallback',reason:...}; public root is /testbed. Parser has no files, executor reads the snapshot only. Schemas require maxLength for strings, maxItems for arrays, properties/required/additionalProperties:false for objects. Operation names are extensible.
Recognize words, synonyms, arguments and constraints, not entire example sentences. Preserve case-sensitive paths and account for exclusions/negation/unknown modifiers. Never silently discard constraints. Defaults must be public in CONTRACT.md. Do not copy answers into executors; compute from files. Reuse helpers and preserve working behavior.
Use bash for your own experiments and tests; it runs Python and fixed tools. For host-reproducible checks, declare tests/cases.json as [{request,files:{'a.txt':'contents'},kind:'completed',text:'expected final text'}, {request,files:{},kind:'unsupported'}]. Include at least two positive variations with differing inputs and a rejection. These are YOUR development assertions, not benchmark certification. Old published tests cannot be removed by editing this file. Check runs return compact failures. You can inspect files and construct any other tests via bash.
When you decide a capability is ready, call capability(action='publish',id=...). That ONE operation snapshots it, reproduces declared and locked regressions and atomically activates on passing checks. No separate activate call or follow-up model confirmation is needed. Failed checks leave the old active version. Do not repeatedly validate a passing unchanged version. Actual active version is the publication result; a passing check alone is not publication. All benchmark testing will use the frozen result; no test-time learning is permitted.`})
 ctx.on('agent/created',({agent})=>{
  agent.ctx.tools.restrict({allow:[]});const defs=[],define=settings.defineTool
  defs.push(define({name:'bash',description:'Execute any shell command inside the persistent isolated development workspace. Read/write code, search, inspect task files, run Python, generate fixtures, run tests. No host/network.',parameters:{command:{type:'string',required:true}},output:{schema:{type:'string'},render:(_a,v)=>[{type:'text',text:v}]},execute:async(a,e)=>JSON.stringify(await dev.command(a.command,e.signal)),timeoutMs:70000}))
  defs.push(define({name:'read_file',description:'Read a UTF-8 development file using the same container as bash.',parameters:{path:{type:'string',required:true}},output:{schema:{type:'string'},render:(_a,v)=>[{type:'text',text:v}]},execute:async(a,e)=>{const payload=Buffer.from(JSON.stringify(a)).toString('base64');return JSON.stringify(await dev.command(`python3 -c 'import json,base64;print(open(json.loads(base64.b64decode("${payload}"))["path"]).read())'`,e.signal))},timeoutMs:70000}))
  defs.push(define({name:'write_file',description:'Create or replace a UTF-8 file in the isolated development workspace. Writes do not publish.',parameters:{path:{type:'string',required:true},text:{type:'string',required:true}},output:{schema:{type:'string'},render:(_a,v)=>[{type:'text',text:v}]},execute:async(a,e)=>{const payload=Buffer.from(JSON.stringify(a)).toString('base64');return JSON.stringify(await dev.command(`python3 -c 'import json,base64,pathlib;p=json.loads(base64.b64decode("${payload}"));f=pathlib.Path(p["path"]);f.parent.mkdir(parents=True,exist_ok=True);print(f.write_text(p["text"]))'`,e.signal))},timeoutMs:70000}))
  defs.push(define({name:'capability',description:'Check agent-declared tests, atomically publish a chosen package, inspect actual active revisions, or roll back to its parent.',parameters:{action:{type:'string',required:true,enum:['check','publish','status','rollback']},id:{type:'string'},revision:{type:'string'}},output:{schema:{type:'string'},render:(_a,v)=>[{type:'text',text:v}]},execute:async(a,e)=>{try{return JSON.stringify(a.action==='status'?{active:(await store.read()).active}:a.action==='check'?await dev.check(a.id,e.signal):a.action==='publish'?await dev.publish(a.id,e.signal):await dev.rollback(a.id,a.revision))}catch(x){return JSON.stringify({error:x.message})}},timeoutMs:600000}))
  if(curriculum){
   for(const d of defs){const execute=d.execute;d.execute=async(a,e)=>{await curriculum.guardDevelopment();return execute(a,e)}}
   defs.push(define({name:'solve',description:'Execute Bash against the current read-only public task at /testbed. No router, development files, future tasks, host or network.',parameters:{command:{type:'string',required:true}},output:{schema:{type:'string'},render:(_a,v)=>[{type:'text',text:v}]},execute:async(a,e)=>JSON.stringify(await curriculum.solve(a.command,e.signal)),timeoutMs:70000}))
   defs.push(define({name:'training',description:'Receive the first task, submit current answer, or enter/leave an allowed development interval. Same conversation continues; no correctness feedback.',parameters:{action:{type:'string',required:true,enum:['next','submit','begin_development','end_development']},answer:{type:'string'},reason:{type:'string'}},output:{schema:{type:'string'},render:(_a,v)=>[{type:'text',text:v}]},execute:async a=>JSON.stringify(await curriculum.control(a)),timeoutMs:70000}))
  }
  const bodies=new Map();for(const d of defs){agent.ctx.tools.register(d);bodies.set(d.name,d.execute)}installed.set(agent,bodies);assert(ctx.tools.schemas(agent).length===(curriculum?6:4),'Unexpected development tools')
 })
 const original=ctx.llm.adapterStream,prepare=ctx.llm.prepareCall
 ctx.llm.prepareCall=async function(config,signal){return prepare.call(this,{...config,maxTokens:Math.min(config.maxTokens??8000,8000)},signal)}
 ctx.llm.adapterStream=async function*(request,prepared){const input=JSON.stringify(request.messages);assert(input.length<=(settings.curriculum?600000:240000),'Development context limit reached');const call=await store.transaction(s=>{const c=s.sessions[settings.sid];assert(!s.frozen&&c.status==='running'&&c.calls.length<c.maxCalls,'Development call budget exhausted');const id=c.calls.length;c.calls.push({id,status:'started',inputHash:hash(input),inputChars:input.length,startedAt:new Date().toISOString()});return id});let usage,finish,error
 try{for await(const chunk of original.call(this,request,prepared)){if(chunk.type==='usage')usage=chunk.usage;if(chunk.type==='finish')finish=chunk.reason;yield chunk}assert(finish&&!['error','aborted'].includes(finish.kind),'Model call incomplete')}
 catch(e){error=e.message;throw e}
 finally{await store.transaction(s=>{Object.assign(s.sessions[settings.sid].calls[call],{status:error?'error':'done',usage,finish,error});event(s,'development-model',{sid:settings.sid,call,error})})}}
 ctx.provide('autonomousDevelopment',{ready:true});return()=>{ctx.llm.adapterStream=original;ctx.llm.prepareCall=prepare}
}
